// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUyIAnzVAxXj6kwgkkJz3JE2IVHAXCS88',
    appId: '1:320871441213:web:770374635fa914339c5b54',
    messagingSenderId: '320871441213',
    projectId: 'momentum-abbf6',
    authDomain: 'momentum-abbf6.firebaseapp.com',
    storageBucket: 'momentum-abbf6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGzqoOx-_F9RWs83-hcHdqPhhdRZ0CtaE',
    appId: '1:320871441213:android:835c624bc46ebc959c5b54',
    messagingSenderId: '320871441213',
    projectId: 'momentum-abbf6',
    storageBucket: 'momentum-abbf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTW_zn8nGtCRcxv8WGhpU0VuKnqxAF6gE',
    appId: '1:320871441213:ios:1f273d357467b63d9c5b54',
    messagingSenderId: '320871441213',
    projectId: 'momentum-abbf6',
    storageBucket: 'momentum-abbf6.firebasestorage.app',
    iosBundleId: 'com.example.momentum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTW_zn8nGtCRcxv8WGhpU0VuKnqxAF6gE',
    appId: '1:320871441213:ios:1f273d357467b63d9c5b54',
    messagingSenderId: '320871441213',
    projectId: 'momentum-abbf6',
    storageBucket: 'momentum-abbf6.firebasestorage.app',
    iosBundleId: 'com.example.momentum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUyIAnzVAxXj6kwgkkJz3JE2IVHAXCS88',
    appId: '1:320871441213:web:98004c511e632e379c5b54',
    messagingSenderId: '320871441213',
    projectId: 'momentum-abbf6',
    authDomain: 'momentum-abbf6.firebaseapp.com',
    storageBucket: 'momentum-abbf6.firebasestorage.app',
  );
}
